server:
  port: 8080  # Порт, на котором будет работать Spring Boot приложение

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'  # Формат даты для JSON
    time-zone: UTC  # Часовой пояс UTC
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap-servers}  # Адреса Kafka брокеров (берётся из переменной)
    listener:
      retry:
        interval: 1000  # Интервал между попытками повтора (1 сек)
        max-attempts: 3  # Максимальное количество попыток
    consumer:
      group-id: message-group  # ID группы потребителей
      auto-offset-reset: earliest  # Чтение с начала топика при отсутствии offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Десериализатор ключа
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # Десериализатор значения
      properties:
        spring.json.type.mapping: >-  # Маппинг типов для десериализации
          request:com.example.messagingapp.dto.MessageRequest,
          response:com.example.messagingapp.dto.MessageResponse
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Сериализатор ключа
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Сериализатор значения
  flyway:
    enabled: true  # Включение Flyway
    user: postgres  # Пользователь БД для Flyway
    password: postgres  # Пароль для Flyway
    url: jdbc:postgresql://postgres:5432/postgres  # URL БД для Flyway
    locations: classpath:db/migration  # Расположение миграций
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres  # URL основной БД
    username: postgres  # Пользователь основной БД
    password: postgres  # Пароль основной БД
    driver-class-name: org.postgresql.Driver  # Драйвер PostgreSQL
  jpa:
    hibernate:
      ddl-auto: validate  # Режим работы Hibernate (валидация схемы)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект PostgreSQL
        format_sql: true  # Форматирование SQL в логах
    show-sql: true  # Показывать SQL в логах

app:
  kafka:
    input-topic: input-messages  # Название входного топике Kafka
    output-topic: output-messages  # Название выходного топика Kafka
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094  # Адреса Kafka брокеров

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Путь к Swagger UI
    enabled: true  # Включение Swagger UI
    tagsSorter: alpha  # Сортировка тегов по алфавиту
    operationsSorter: alpha  # Сортировка операций по алфавиту
  api-docs:
    path: /api-docs  # Путь к OpenAPI спецификации
    version: openapi_3_1  # Версия OpenAPI


logging:
  level:
    org.hibernate.SQL: DEBUG  # Уровень логирования SQL запросов
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Уровень логирования параметров SQL
    root: INFO  # Общий уровень логирования
    org.springframework: INFO  # Уровень логирования Spring
    org.apache.kafka: INFO  # Уровень логирования Kafka
    com.example.messagingapp: INFO  # Уровень логирования вашего приложения
  file:
    name: app/logs/application.log  # Путь к файлу логов
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # Формат логов в файле
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"  # Формат логов в консоли

resilience4j:
  circuitbreaker:           # Основная секция для настройки Circuit Breaker
    instances:             # Определение конкретных экземпляров Circuit Breaker
      kafkaProducer:       # Имя экземпляра (используется в @CircuitBreaker(name = "kafkaProducer"))
        # Тип скользящего окна для подсчета ошибок
        sliding-window-type: COUNT_BASED  # Альтернатива: TIME_BASED (анализ за временной промежуток)
        # Размер окна для анализа ошибок
        sliding-window-size: 10  # Анализировать последние 10 вызовов
        # Минимальное количество вызовов перед активацией CB
        minimum-number-of-calls: 5  # Нужно минимум 5 вызовов для анализа статистики
        # Порог процента ошибок для размыкания цепи
        failure-rate-threshold: 50  # Размыкать цепь при 50% ошибок в окне
        # Время в разомкнутом состоянии
        wait-duration-in-open-state: 30s  # После размыкания ждать 30 секунд перед попыткой восстановления
        # Количество тестовых запросов в полуоткрытом состоянии
        permitted-number-of-calls-in-half-open-state: 3  # Пропустить 3 запроса для проверки восстановления
        # Исключения, которые считаются ошибками для CB
        record-exceptions:
          - org.springframework.kafka.KafkaException  # Все исключения Kafka
          - java.util.concurrent.TimeoutException     # Таймауты при работе с Kafka